auto approve sigma rule update PR
Yamato-Security/hayabusa-rules pull request #140
Opened 2022-10-05 07:39 UTC by YamatoSecurity

App経由でgithub actionを実行しようとしましたが、なぜかreviewバイパスの設定でAppを追加できなかったので、別の方法にしました。元々はGitHubの脆弱性だったようですが、ActionからPRをSelf-Approveできるようなので、これを試したいです。
詳細: https://medium.com/cider-sec/bypassing-required-reviews-using-github-actions-6e1b29135cc7
```      - name: Approve Pull Request
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/reviews \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}'
```

2022-10-05 08:11 UTC, hach1yon requested changes
変更お願いします。

2022-10-05 08:11 UTC, hach1yon commented on .github/workflows/update-sigmarule.yaml
> +        run: |
pull requestをオートマージできるようにするstepが成功した時だけ実行できるようにしないとまずいです。

2022-10-05 08:11 UTC, hach1yon commented on .github/workflows/update-sigmarule.yaml
> +          -d '{"event":"APPROVE"}'
ちゃんと調べてないので分からないのですが、これは正規の方法ですか?マーケットプレイスに出ているgithub actionがあるので、こちらを使った方が良いかも

https://github.com/marketplace/actions/approve-pull-request

2022-10-05 09:01 UTC, YamatoSecurity commented on .github/workflows/update-sigmarule.yaml
> +          -d '{"event":"APPROVE"}'
脆弱性だと指摘されても、わざとそのままデフォルトでself approveできるように有効にしているので、正規の方法だと思います。「脆弱性ではなくて、仕様です」というやつだと思います。

2022-10-05 09:05 UTC, YamatoSecurity commented on .github/workflows/update-sigmarule.yaml
> +        run: |
なるほど。ちょっと見てみます。

2022-10-05 12:14 UTC, YamatoSecurity commented on .github/workflows/update-sigmarule.yaml
> +        run: |
https://github.com/peter-evans/enable-pull-request-automerge を見てみましたが、Actions outputが書かれていないので、どうしたら良いか分かりませんでした。分かりますか？

2022-10-05 13:35 UTC, hach1yon commented on .github/workflows/update-sigmarule.yaml
> +        run: |
やりかたよく分からないので、Enable Pull Request Automergeがskipされずに実行された上で、正常終了したことを条件にしてください。

2022-10-05 13:56 UTC, hach1yon commented on .github/workflows/update-sigmarule.yaml
> +          -d '{"event":"APPROVE"}'
開発者的にはそういう不安要素のあるAPIを使うのはあまりお勧めできないです。

あと、これは試してみないと分からないことですが、`${{github.event.number}}`にpull requestのIDが設定されるのは確認しましたか? pull requestによってトリガーされた場合はここにpull requestのIDの入りますが、そうじゃない時も入るのかどうかよく分からないです。`${{ steps.cpr.outputs.pull-request-number }}`を使う方がコード的にも読み易いと思います。

2022-10-06 03:51 UTC, hach1yon reviewed
あと、英語直してもらえるのは有り難いのですが、本来の変更と交じると分かりにくくなるので、英語の修正は別PRにしてもらえると助かります。

2022-10-09 02:25 UTC, hitenkoku commented
@YamatoSecurity 自動で出てくるpull requestですが、設定としてmainがprotect branchになっているため自動マージができてなさそうですが、mainブランチのプロテクトを外してはどうでしょうか？

2022-10-09 09:29 UTC, YamatoSecurity commented
@hitenkoku そうですね。それを避けようと思っていましたが、思ったより色々面倒なので、そうしましょうか？普段は私しか更新していないので、複数のcollaboratorのhayabusaレポほど注意しなくても良いと思います→protect branchを外しても問題なさそうです。
@hach1yon どうですか？

2022-10-09 10:12 UTC, hach1yon commented
セキュリティ的に問題ないと思えば、それで良いと思います。

2022-10-10 00:14 UTC, YamatoSecurity commented
了解です。では、自動更新のworkflowは今のままでbranch protectionの設定変更で対応します。
@hach1yon このPRで色々対応してくれてありがとうございました。お手数をかけて申し訳ありませんでした。

2022-10-10 00:14 UTC, closed without merging